# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Uber-Lyft-Compare-Prices' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'LyftSDK'
  pod 'UberRides', '~> 0.9'

  # Pods for Uber-Lyft-Compare-Prices

  target 'Uber-Lyft-Compare-PricesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Uber-Lyft-Compare-PricesUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end


